language: r

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - testthat

r_github_packages:
  - jimhester/lintr

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

after_success:
  - Rscript -e "covr::codecov(line_exclusions = list('R/zzz.R', 'R/demo.R'))"
