#!/bin/bash

echo "Cleaning up..."
rm -rf \
	config.* \
	Makefile.in \
	aclocal* \
	compile \
	autom* \
	install-sh \
	depcomp \
	missing \
	test-driver \
	Makefile \
	src/netReg.so \
	src/config.h \
	src/.deps \
	src/stamp-h1 \
	stamp-h1 \
	src/Makevars \
	src/stamp-h1

find src -name *.so -delete
find src -name *.a -delete
find src -name *.o -delete
find src -name *.dirstamp -delete
